runtime: nodejs10
env: standard

service: test-mongodb
# service: demo
# service: default

env_variables:
  DATABASE_URL: 'mongodb://172.16.0.4/'

vpc_access_connector:
  name: 'projects/cloudiv2/locations/us-east1/connectors/testeinterno'